### ISSUE TITLE
Construcción de modelo de datos

### ISSUE THREAD

**Issue by IdleTimeUTB** [ISCOUTB/AH-MetroEvent#1]

**Comment by anto16jose** [comment]
[Modelo de Datos.pdf](https://github.com/user-attachments/files/16930720/Modelo.de.Datos.pdf)

**Comment by anto16jose** [comment]
![Image](https://github.com/user-attachments/assets/82f79b69-57f0-4295-a9af-757ab9a79978)

**Comment by jairoserrano** [comment]
adelante.
