### ISSUE TITLE
Construcción de diagrama E-R

### ISSUE THREAD

**Issue by David05R** [ISCOUTB/AH-MetroEvent#2]

**Comment by anto16jose** [comment]
![Image](https://github.com/user-attachments/assets/5de09b72-8d0f-4dc8-af2e-1d626688b336)

**Comment by anto16jose** [comment]
![Image](https://github.com/user-attachments/assets/9c7875c9-e027-4732-9e02-dd7ae718bf91)

**Comment by jairoserrano** [comment]
adelante
