### ISSUE TITLE
Desarrollo del mockup de la interfaz visual

### ISSUE THREAD

**Issue by David05R** [ISCOUTB/AH-MetroEvent#5]

**Comment by David05R** [comment]
El mockup fue realizado en la plataforma de diseño Figma, en el siguiente link podrá visualizar el diseño:

https://www.figma.com/design/gam1MozWVOx4JeNWli4BWQ/Arquitectura---MetroEvents?node-id=0-1&t=1PnX8jsxWBOxlBR8-1

**Comment by jairoserrano** [comment]
adelante
